name: moneymanager
description: Money Manager app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <3.38.5'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^2.1.1
  riverpod_annotation: ^2.3.3
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  emoji_picker_flutter: ^3.0.0
  flutter_svg: ^2.0.9
  currency_picker: ^2.0.14
  shared_preferences: ^2.0.17
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  equatable: ^2.0.0
  collection: ^1.16.0
  intl: ^0.20.2
  flutter_time_picker_spinner: ^2.0.0
  rxdart: ^0.28.0
  jiffy: ^6.2.1
  path_provider: ^2.1.1
  package_info_plus: ^8.0.2
  function_tree: ^0.9.1
  auto_size_text: ^3.0.0
  file: ^7.0.0
  share_plus: ^11.0.0
  file_picker: ^10.1.9
  syncfusion_flutter_charts: ^30.2.4
  sentry_flutter: ^9.6.0
  firebase_core: ^4.1.1
  firebase_analytics: ^12.0.2
  local_auth: ^3.0.0
  flutter_secure_storage: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  mocktail: ^1.0.2
  build_runner: ^2.3.3
  riverpod_generator: ^2.3.9
  isar_generator: ^3.1.0+1
  flutter_lints: ^4.0.0
  freezed: ^2.3.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/defaults/categories.json
